suites:
- name: bb_chef_server
  driver_config:
    image_name: <%= ENV['LXD_IMAGE_NAME'] || 'bb_chef_server-ubuntu-14.04-static-ip' %>
    ipv4: 10.100.0.11/24
  run_list:
  - recipe[bb_chef_server]
  attributes:
