---
driver:
  name: lxd_cli
  publish_image_name: "bb-chef-server-ubuntu-1404"
  use_publish_image: true
  publish_image_before_destroy: true
  publish_image_overwrite: true

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04

suites:
- name: bb_chef_server
  run_list:
  - recipe[bb_chef_server]
  attributes:
